"""
CombineMain — stitch the post-processing outputs of multiple MAES runs into a
single combined output, as if all sites had been simulated together.

Use case: split a large site batch (e.g. 10k sites) into smaller per-walltime
batches, run each one separately on HPC, then combine the outputs here so that
downstream analysis sees a single MC_<timestamp>-style directory.

Constraints enforced by preflight:
  - identical monteCarloIterations, simDurationDays, factorName across inputs
  - the same set of abnormal modes ('ON'/'OFF') was generated by each input
  - the site sets across inputs are pairwise disjoint (no site collisions)
  - basic schema agreement on the parquet metadata column set

What gets combined:
  - parquet datasets (site/facilityID-partitioned)         -> symlink partitions
  - per-site summary CSV trees                              -> symlink directories
  - per-site template/ directories                          -> symlink directories
  - simulation-wide aggregated summaries + CDF plot         -> RECOMPUTED from
                                                               the combined data

Per-MC iteration CSVs (events/ts/gc/...) are NOT carried over — nothing in
post-processing reads them.

CLI:
    python CombineMain.py \
        --inputs <input_root_1> <input_root_2> ... \
        --output <combined_root> \
        [--abnormal ON OFF] \
        [--copy-instead-of-symlink] \
        [--verbose]
"""

import argparse
import json
import logging
import os
import shutil
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Optional, Set, Tuple

import pandas as pd

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# parquet datasets partitioned by `site=`
PARQUET_DATASETS_BY_SITE = [
    "events",
    "eventList",
    "timeseries",
    "gascomposition",
    "metadata",
    "simsummary",
]

# parquet datasets partitioned by `facilityID=`
PARQUET_DATASETS_BY_FACILITY = [
    "siteEmissionsbyCat",
    "siteEmissionsByEquip",
    "siteInstantEmissionsByEquip",
    "averageEmissionMetrics",
]

# per-site summary subtrees under summaries/  (each contains site=<X>/ dirs)
SUMMARY_SUBTREES_BY_SITE = [
    "AnnualEmissions",
    "InstantaneousEmissions",
    "AvgEmissionRatesAndDurations",
    "PDFs",
]

# simulation-wide aggregated outputs that must be regenerated
AGGREGATED_SUBTREE = "AggregatedSimulationEmissions"

# minimum config fields that must match across all input runs
CONFIG_FIELDS_MUST_MATCH = [
    "monteCarloIterations",
    "simDurationDays",
    "factorName",
]

# config fields used for the recomputation step (taken from the first input)
CONFIG_FIELDS_FOR_AGG = [
    "monteCarloIterations",
    "simDurationDays",
    "factorName",
    "studyName",
    "abnormal",
    "fullSummaries",
    "annualSummaries",
    "simulationEmissions",
    "plot",
]

# basenames of marker files we proactively clean from the combined output
SIMAGG_MARKER_PREFIX = ".simagg_"

logger = logging.getLogger("CombineMain")


# ---------------------------------------------------------------------------
# Error type
# ---------------------------------------------------------------------------

class CombineError(Exception):
    """Raised on any unrecoverable problem during combine.

    `details` is a dict that gets logged and embedded in combine_manifest.json
    so failures are debuggable after the fact.
    """

    def __init__(self, message: str, **details):
        super().__init__(message)
        self.details = details

    def __str__(self) -> str:
        if not self.details:
            return super().__str__()
        kv = ", ".join(f"{k}={v!r}" for k, v in self.details.items())
        return f"{super().__str__()} [{kv}]"


# ---------------------------------------------------------------------------
# Input discovery + preflight
# ---------------------------------------------------------------------------

@dataclass
class InputRun:
    """One MAES simulation root we're folding into the combined output."""
    root: Path                       # e.g. .../output/CO_2026/MC_20260601_120000
    config: Dict[str, str]           # parsed key,value from config.csv
    sites: Set[str]                  # set of site names discovered in parquet
    abnormal_modes: Set[str]         # set of 'on' / 'off' found in AggregatedSimulationEmissions
    metadata_columns: Optional[List[str]] = None  # from parquet/metadata schema

    @property
    def label(self) -> str:
        return self.root.name


def _read_config_csv(root: Path) -> Dict[str, str]:
    """Locate any config.csv under {root}/{site}/{mc}/ and load it.

    Per-MC config.csvs are identical within a run (they're snapshots of the
    same workitem config). We just grab the first one.
    """
    candidates = sorted(root.glob("*/*/config.csv"))
    if not candidates:
        raise CombineError(
            "no config.csv found under input root; cannot validate input",
            root=str(root),
        )
    df = pd.read_csv(candidates[0])
    if "key" not in df.columns or "value" not in df.columns:
        raise CombineError(
            "config.csv has unexpected columns; expected 'key' and 'value'",
            path=str(candidates[0]),
            columns=list(df.columns),
        )
    # value column is read as object; everything stays as strings for compare
    cfg = dict(zip(df["key"].astype(str), df["value"].astype(str)))
    return cfg


def _discover_sites(root: Path) -> Set[str]:
    """Site names are the partition values under parquet/events/site=*"""
    events_dir = root / "parquet" / "events"
    if not events_dir.exists():
        raise CombineError(
            "input has no parquet/events directory; was the parquet phase run?",
            root=str(root),
            looked_at=str(events_dir),
        )
    sites = set()
    for child in events_dir.iterdir():
        if child.is_dir() and child.name.startswith("site="):
            sites.add(child.name[len("site="):])
    if not sites:
        raise CombineError(
            "input has parquet/events but no site=<...> partitions in it",
            root=str(root),
        )
    return sites


def _discover_abnormal_modes(root: Path) -> Set[str]:
    """Look at filenames under summaries/AggregatedSimulationEmissions/ to see
    which abnormal modes were generated."""
    agg = root / "summaries" / AGGREGATED_SUBTREE
    modes: Set[str] = set()
    if not agg.exists():
        return modes
    for f in agg.iterdir():
        name = f.name.lower()
        if name.endswith("_abnormal_on.csv"):
            modes.add("on")
        elif name.endswith("_abnormal_off.csv"):
            modes.add("off")
    return modes


def _discover_metadata_columns(root: Path) -> Optional[List[str]]:
    """Read the schema of one metadata parquet to sanity-check column set."""
    md_dir = root / "parquet" / "metadata"
    if not md_dir.exists():
        return None
    files = list(md_dir.rglob("*.parquet"))
    if not files:
        return None
    try:
        import pyarrow.parquet as pq
        schema = pq.read_schema(files[0])
        return [f.name for f in schema]
    except Exception as e:  # pragma: no cover - schema read failure is non-fatal
        logger.warning("could not read metadata schema for %s: %s", root, e)
        return None


def discover_input(root: Path) -> InputRun:
    """Load all preflight-relevant facts about one input run."""
    if not root.exists() or not root.is_dir():
        raise CombineError("input root does not exist or is not a directory",
                           root=str(root))
    config = _read_config_csv(root)
    sites = _discover_sites(root)
    modes = _discover_abnormal_modes(root)
    md_cols = _discover_metadata_columns(root)
    logger.info("Discovered input %s: %d sites, abnormal modes=%s",
                root.name, len(sites), sorted(modes) or "(none)")
    return InputRun(root=root, config=config, sites=sites,
                    abnormal_modes=modes, metadata_columns=md_cols)


def preflight(inputs: List[InputRun]) -> None:
    """Verify all six combine constraints. Raises CombineError on any failure
    with structured details that point at the offending input(s)."""
    if len(inputs) < 2:
        raise CombineError(
            "combine requires at least two input runs",
            num_inputs=len(inputs),
        )

    # 1-3. config fields that must match across all inputs
    for field_name in CONFIG_FIELDS_MUST_MATCH:
        seen: Dict[str, List[str]] = {}
        for inp in inputs:
            v = inp.config.get(field_name)
            if v is None:
                raise CombineError(
                    f"input is missing required config field '{field_name}'",
                    input=inp.label,
                )
            seen.setdefault(v, []).append(inp.label)
        if len(seen) > 1:
            raise CombineError(
                f"input runs disagree on config field '{field_name}'",
                field=field_name,
                values={v: labels for v, labels in seen.items()},
            )

    # 4. abnormal mode coverage — every input must have the same set of modes
    mode_groups: Dict[Tuple[str, ...], List[str]] = {}
    for inp in inputs:
        key = tuple(sorted(inp.abnormal_modes))
        mode_groups.setdefault(key, []).append(inp.label)
    if len(mode_groups) > 1:
        raise CombineError(
            "input runs disagree on which abnormal modes were generated",
            mode_groups={"+".join(k) or "(none)": v
                         for k, v in mode_groups.items()},
        )
    common_modes = next(iter(mode_groups.keys()))
    if not common_modes:
        logger.warning("no abnormal-mode AggregatedSimulationEmissions found "
                       "in any input — sim-wide recomputation will be skipped")

    # 5. site sets must be pairwise disjoint
    site_to_inputs: Dict[str, List[str]] = {}
    for inp in inputs:
        for s in inp.sites:
            site_to_inputs.setdefault(s, []).append(inp.label)
    collisions = {s: labels for s, labels in site_to_inputs.items()
                  if len(labels) > 1}
    if collisions:
        # show at most 10 colliding sites to keep the message readable
        sample = dict(list(collisions.items())[:10])
        raise CombineError(
            f"{len(collisions)} site(s) appear in more than one input — "
            f"combine requires disjoint site sets",
            colliding_sites_sample=sample,
            total_collisions=len(collisions),
        )

    # 6. metadata schema agreement (warn-only on minor drift; fail on big drift)
    col_sets = {inp.label: set(inp.metadata_columns or []) for inp in inputs}
    base_label, base_cols = next(iter(col_sets.items()))
    for label, cols in col_sets.items():
        if not cols:
            continue
        only_in_base = base_cols - cols
        only_in_other = cols - base_cols
        if only_in_base or only_in_other:
            # Schema drift is suspicious enough to refuse the combine — it
            # usually means inputs were generated by different MAES versions
            # or different model formulations.
            raise CombineError(
                "metadata parquet schema differs between inputs",
                first_input=base_label,
                second_input=label,
                only_in_first=sorted(only_in_base),
                only_in_second=sorted(only_in_other),
            )

    logger.info("Preflight passed: %d inputs, %d total sites, modes=%s",
                len(inputs),
                sum(len(i.sites) for i in inputs),
                sorted(common_modes) or "(none)")


# ---------------------------------------------------------------------------
# File operations (symlink or copy)
# ---------------------------------------------------------------------------

def _make_link_fn(use_copy: bool) -> Callable[[Path, Path], None]:
    """Returns a function(src, dst) that places src's contents at dst.
    Both src and dst are directories (or files inside a partitioned dataset).
    The function is idempotent: it skips dst if already present.
    """
    if use_copy:
        def _copy(src: Path, dst: Path) -> None:
            if dst.exists():
                logger.debug("skip copy (exists): %s", dst)
                return
            dst.parent.mkdir(parents=True, exist_ok=True)
            if src.is_dir():
                shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)
        return _copy

    def _symlink(src: Path, dst: Path) -> None:
        if dst.exists() or dst.is_symlink():
            logger.debug("skip symlink (exists): %s", dst)
            return
        dst.parent.mkdir(parents=True, exist_ok=True)
        # Use absolute target so the combined dir can be relocated without
        # breaking links (links still depend on the source paths existing).
        os.symlink(os.path.abspath(src), dst)
    return _symlink


# ---------------------------------------------------------------------------
# Tier 1 + 2 — stitch parquet partitions and per-site summary trees
# ---------------------------------------------------------------------------

def _link_partition_dirs(inputs: List[InputRun],
                         combined_root: Path,
                         relative_dataset: Path,
                         partition_prefix: str,
                         link_fn: Callable[[Path, Path], None]) -> int:
    """For each input, link every partition directory matching
    `partition_prefix` (e.g. 'site=' or 'facilityID=') under
    {input}/relative_dataset into the same place under combined_root.
    Returns the count of partitions linked.
    """
    count = 0
    target_base = combined_root / relative_dataset
    for inp in inputs:
        src_base = inp.root / relative_dataset
        if not src_base.exists():
            logger.debug("input %s has no %s — skipping", inp.label,
                         relative_dataset)
            continue
        for child in src_base.iterdir():
            if not (child.is_dir() and child.name.startswith(partition_prefix)):
                continue
            dst = target_base / child.name
            link_fn(child, dst)
            count += 1
    return count


def link_parquet_datasets(inputs: List[InputRun], combined_root: Path,
                          link_fn: Callable[[Path, Path], None]) -> Dict[str, int]:
    """Tier 1: link every site/facilityID partition from every parquet dataset
    in every input into the combined output. Returns per-dataset counts."""
    counts: Dict[str, int] = {}
    for ds in PARQUET_DATASETS_BY_SITE:
        counts[ds] = _link_partition_dirs(
            inputs, combined_root, Path("parquet") / ds, "site=", link_fn)
    for ds in PARQUET_DATASETS_BY_FACILITY:
        counts[ds] = _link_partition_dirs(
            inputs, combined_root, Path("parquet") / ds, "facilityID=", link_fn)
    for ds, n in counts.items():
        logger.info("parquet/%s: linked %d partitions", ds, n)
    return counts


def link_per_site_summaries(inputs: List[InputRun], combined_root: Path,
                            link_fn: Callable[[Path, Path], None]
                            ) -> Dict[str, int]:
    """Tier 2: each per-site summary subtree contains site=<X>/ dirs. Link
    each of those into the combined output's matching subtree."""
    counts: Dict[str, int] = {}
    for subtree in SUMMARY_SUBTREES_BY_SITE:
        counts[subtree] = _link_partition_dirs(
            inputs, combined_root, Path("summaries") / subtree,
            "site=", link_fn)
    for subtree, n in counts.items():
        logger.info("summaries/%s: linked %d site dirs", subtree, n)
    return counts


# ---------------------------------------------------------------------------
# Tier 4 — copy templates (small, useful for restartability)
# ---------------------------------------------------------------------------

def link_site_templates(inputs: List[InputRun], combined_root: Path,
                        link_fn: Callable[[Path, Path], None]) -> int:
    """Each input has {site}/template/ per site. We don't carry per-MC dirs,
    but templates are tiny and useful for restartability."""
    count = 0
    for inp in inputs:
        for site in sorted(inp.sites):
            src = inp.root / site / "template"
            if not src.exists():
                logger.debug("no template dir for site %s under %s",
                             site, inp.label)
                continue
            dst = combined_root / site / "template"
            link_fn(src, dst)
            count += 1
    logger.info("templates: linked %d per-site template dirs", count)
    return count


# ---------------------------------------------------------------------------
# Tier 3 — recompute simulation-wide aggregations
# ---------------------------------------------------------------------------

def _clear_sim_agg_markers(combined_root: Path) -> None:
    """The in-process guards in Summaries.py also write .simagg_*.done files
    to detect already-completed work across processes. Any such markers in
    the combined output would suppress the recomputation we want to run.
    """
    removed = 0
    for marker in combined_root.glob(f"{SIMAGG_MARKER_PREFIX}*"):
        try:
            if marker.is_dir():
                shutil.rmtree(marker)
            else:
                marker.unlink()
            removed += 1
        except OSError as e:
            logger.warning("could not remove stale marker %s: %s", marker, e)
    if removed:
        logger.info("cleared %d stale sim-agg marker(s) in combined root",
                    removed)


def _build_agg_config(inputs: List[InputRun],
                      combined_root: Path) -> Dict[str, object]:
    """Synthesize the config dict that the sim-wide aggregation functions
    expect. Pulls values from the first input (preflight has already verified
    they agree across inputs)."""
    base = inputs[0].config
    cfg: Dict[str, object] = {
        "simulationRoot": str(combined_root),
        "parquetDir": str(combined_root / "parquet"),
        "parquetEventDS":          str(combined_root / "parquet" / "events"),
        "parquetEventListDS":      str(combined_root / "parquet" / "eventList"),
        "parquetTimeseriesDS":     str(combined_root / "parquet" / "timeseries"),
        "parquetGasCompositionDS": str(combined_root / "parquet" / "gascomposition"),
        "parquetMetadataDS":       str(combined_root / "parquet" / "metadata"),
        "parquetSummaryDS":        str(combined_root / "parquet" / "simsummary"),
        # siteEmissions is a dynamic template — recreate the structure
        # dumpEmissions / Aggregated* functions write under
        # {simulationRoot}/summaries/AggregatedSimulationEmissions/
        "siteEmissions": str(combined_root / "{facilityID}.csv"),
    }
    # Copy through anything the agg functions might read
    for k in CONFIG_FIELDS_FOR_AGG:
        if k in base:
            cfg[k] = base[k]
    try:
        cfg["simDurationDays"] = float(cfg.get("simDurationDays", 0)) \
            if cfg.get("simDurationDays") else None
    except (TypeError, ValueError):
        cfg["simDurationDays"] = None
    return cfg


def recompute_sim_wide(combined_root: Path,
                       inputs: List[InputRun],
                       abnormal_modes: Iterable[str]) -> Dict[str, int]:
    """Tier 3: re-drive the five existing sim-wide functions on the combined
    parquet for each abnormal mode."""
    # Import Summaries lazily so failures importing the rest of MAES don't
    # block earlier stages (e.g. preflight / linking).
    try:
        import Summaries as sm
    except Exception as e:
        raise CombineError(
            "failed to import Summaries.py; cannot recompute sim-wide outputs",
            error=str(e),
        )

    _clear_sim_agg_markers(combined_root)
    cfg = _build_agg_config(inputs, combined_root)
    sim_duration_days = cfg.get("simDurationDays")
    results: Dict[str, int] = {}

    for mode_lower in abnormal_modes:
        mode = mode_lower.upper()
        logger.info("Recomputing sim-wide aggregations for abnormal=%s", mode)
        try:
            sm.run_emissions_summary_pipeline_for_modelReadableName_and_unitID(
                folder=str(combined_root), abnormal=mode,
                simDurationDays=sim_duration_days,
            )
            sm.run_total_emissions_pipeline_for_category(
                folder=str(combined_root), abnormal=mode,
                simDurationDays=sim_duration_days,
            )
            sm.run_emissions_summary_pipeline_for_metype(
                folder=str(combined_root), abnormal=mode,
                simDurationDays=sim_duration_days,
            )
            sm.generate_site_level_pdfs(
                root_dir=str(combined_root), site=None, abnormal=mode,
            )
            results[mode] = 4  # number of CSV pipelines run
        except Exception as e:
            raise CombineError(
                f"sim-wide aggregation failed for abnormal={mode}",
                error=str(e),
            )

    # Optional CDF plot — only if both modes were generated and plot was
    # requested in the original config.
    if "on" in abnormal_modes and "off" in abnormal_modes:
        try:
            sm.generate_comnbined_cdf_plot(cfg)
            logger.info("Generated combined CDF plot")
            results["cdf_plot"] = 1
        except Exception as e:
            logger.warning("Combined CDF plot generation failed: %s", e)

    return results


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------

def write_manifest(combined_root: Path,
                   inputs: List[InputRun],
                   counts: Dict[str, object],
                   timings: Dict[str, float],
                   link_mode: str) -> None:
    """combine_manifest.json records what was combined, when, with which
    settings, and how many files moved through each stage. Crucial for
    debugging stitched outputs months later."""
    manifest = {
        "combined_root": str(combined_root),
        "generated_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "link_mode": link_mode,
        "inputs": [
            {
                "root": str(inp.root),
                "label": inp.label,
                "site_count": len(inp.sites),
                "abnormal_modes": sorted(inp.abnormal_modes),
                "config": {k: inp.config.get(k) for k in CONFIG_FIELDS_MUST_MATCH},
            }
            for inp in inputs
        ],
        "totals": {
            "input_count": len(inputs),
            "total_sites": sum(len(i.sites) for i in inputs),
        },
        "stage_counts": counts,
        "stage_timings_seconds": {k: round(v, 3) for k, v in timings.items()},
    }
    path = combined_root / "combine_manifest.json"
    with open(path, "w") as f:
        json.dump(manifest, f, indent=2, default=str)
    logger.info("Wrote %s", path)


# ---------------------------------------------------------------------------
# Orchestration + CLI
# ---------------------------------------------------------------------------

def combine(input_roots: List[Path],
            combined_root: Path,
            abnormal_override: Optional[List[str]] = None,
            use_copy: bool = False) -> None:
    """Top-level combine flow. Each stage is timed and logged."""
    timings: Dict[str, float] = {}
    counts: Dict[str, object] = {}

    t0 = time.time()
    inputs = [discover_input(p) for p in input_roots]
    timings["discover"] = time.time() - t0

    t0 = time.time()
    preflight(inputs)
    timings["preflight"] = time.time() - t0

    combined_root.mkdir(parents=True, exist_ok=True)
    link_fn = _make_link_fn(use_copy)
    link_mode = "copy" if use_copy else "symlink"

    t0 = time.time()
    counts["parquet"] = link_parquet_datasets(inputs, combined_root, link_fn)
    timings["link_parquet"] = time.time() - t0

    t0 = time.time()
    counts["summaries_per_site"] = link_per_site_summaries(
        inputs, combined_root, link_fn)
    timings["link_summaries"] = time.time() - t0

    t0 = time.time()
    counts["templates"] = link_site_templates(inputs, combined_root, link_fn)
    timings["link_templates"] = time.time() - t0

    # Determine abnormal modes for recomputation
    if abnormal_override:
        modes = [m.lower() for m in abnormal_override]
    else:
        # use the (preflight-verified) common set across all inputs
        modes = sorted(inputs[0].abnormal_modes)

    if modes:
        t0 = time.time()
        counts["sim_wide_recompute"] = recompute_sim_wide(
            combined_root, inputs, modes)
        timings["sim_wide_recompute"] = time.time() - t0
    else:
        logger.warning("No abnormal modes to recompute — skipping Tier 3. "
                       "Combined output will lack AggregatedSimulationEmissions.")
        counts["sim_wide_recompute"] = {}

    t0 = time.time()
    write_manifest(combined_root, inputs, counts, timings, link_mode)
    timings["manifest"] = time.time() - t0

    total = sum(timings.values())
    logger.info("Combine complete in %.2fs. Output: %s",
                total, combined_root)


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="CombineMain",
        description=("Stitch the outputs of multiple MAES runs into one "
                     "combined output root. See module docstring for details."),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--inputs", nargs="+", required=True,
                   help="Two or more MAES output roots (e.g. MC_<timestamp> dirs)")
    p.add_argument("--output", required=True,
                   help="Path to the combined output root (will be created)")
    p.add_argument("--abnormal", nargs="+", choices=["ON", "OFF", "on", "off"],
                   default=None,
                   help=("Restrict sim-wide recomputation to these modes "
                         "instead of the inputs' common set."))
    p.add_argument("--copy-instead-of-symlink", action="store_true",
                   help=("Copy files instead of symlinking. Combined dir "
                         "becomes self-contained but uses much more disk."))
    p.add_argument("--verbose", action="store_true",
                   help="Enable DEBUG logging.")
    return p.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    try:
        combine(
            input_roots=[Path(p).resolve() for p in args.inputs],
            combined_root=Path(args.output).resolve(),
            abnormal_override=args.abnormal,
            use_copy=args.copy_instead_of_symlink,
        )
    except CombineError as e:
        logger.error("Combine failed: %s", e)
        if e.details:
            logger.error("Failure details: %s",
                         json.dumps(e.details, indent=2, default=str))
        return 2
    except Exception:
        logger.exception("Unexpected error during combine")
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main())
