name: Release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.3"

      - name: Install dependencies
        run: pip install build poetry-core

      - name: Build package
        run: python -m build

      - name: Get the latest tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Zip Input Study Sheets
        run: zip -r "input-${TAG}.zip" input

      - name: Upload Input Study Sheets
        uses: actions/upload-artifact@v4
        with:
          name: input-${{ env.TAG }}.zip
          path: input-${{ env.TAG }}.zip
          retention-days: 400

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 400

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ env.CHANGELOG }}
          files: |
            dist/*.whl
            dist/*.tar.gz
            input-${{ env.TAG }}.zip
          draft: false
          generate_release_notes: true
